#  http://paulstamatiou.com/how-to-wordpress-to-jekyll
#
source: .
destination: ./_site

markdown: redcarpet

highlighter: pygments

base_url: http://adamobeng.com
description: "Adam Obeng's Website"
root_desc: "adamobeng.com"

exclude: ['config.rb', 'references', 'convert', 'sass', '_drafts']
permalink: ":title"
